name: e_commerce_mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  toastification: ^3.0.3
  provider: ^6.1.2
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.2
  flutter_bloc: ^9.1.1
  flutter_html: ^3.0.0
  cached_network_image: ^3.2.3
  skeletonizer: ^2.1.3
  path_provider: ^2.1.0
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  get_it: ^8.0.2
  dartz: ^0.10.1
  image_picker: ^1.1.2
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^12.0.1
  url_launcher: ^6.3.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.17.0
  mobile_scanner: ^7.2.0
  sqflite: ^2.4.2
  path: ^1.9.0
  uuid: ^4.5.1
  flutter_polyline_points: ^2.0.1
  intl: ^0.20.2
  local_auth: ^3.0.1
  local_auth_android: ^2.0.8
  local_auth_darwin: ^2.0.3
  flutter_secure_storage: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/logo.png
    - assets/images/profile.png
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter[opsz,wght].ttf
        - asset: assets/fonts/Inter/Inter-Italic[opsz,wght].ttf
          style: italic
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang/Battambang-Thin.ttf
          weight: 100
        - asset: assets/fonts/Battambang/Battambang-Light.ttf
          weight: 300
        - asset: assets/fonts/Battambang/Battambang-Regular.ttf
          weight: 400
        - asset: assets/fonts/Battambang/Battambang-Bold.ttf
          weight: 700
        - asset: assets/fonts/Battambang/Battambang-Black.ttf
          weight: 900
    - family: KhmerOSSiemreap
      fonts:
        - asset: assets/fonts/KhmerOSSiemreap/KhmerOSSiemreap.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/logo.png"
  remove_alpha: false
  remove_alpha_ios: false
